version: '3'

services:

  b3newsapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - b3newsdatabase:/home/b3newsdb
    expose:
      - "80"
    ports:
      - "80:80"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile

volumes:
  b3newsdatabase:
